/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbox;

/**
 *
 * @author victo
 */
public class Resultados extends javax.swing.JFrame {

    Pelea re = new Pelea();

    /**
     * Creates new form Resultados
     */
    public Resultados(Pelea pe) {
        initComponents();
        re = pe;
        this.setLocationRelativeTo(null);
        imprimirCalificaciones();
    }

    // Método para imprimir todas las calificaciones de cada juez
    public void imprimirCalificaciones() {
        for (int i = 0; i < re.ju.length; i++) {
            System.out.println("=== Juez " + (i + 1) + " ===");

            System.out.print("Peleador 1: ");
            for (Integer p : re.ju[i].puntos1) {
                System.out.print(p + " ");
            }
            System.out.println(); // salto de línea

            System.out.print("Peleador 2: ");
            for (Integer p : re.ju[i].puntos2) {
                System.out.print(p + " ");
            }
            System.out.println("\n"); // doble salto para separar jueces
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
