package appbox;

import java.util.Random;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author victo
 */
public class Round extends javax.swing.JFrame {

    int c = 1;
    Pelea nuevaPelea = new Pelea();

    /**
     * Contructor
     */
    public Round(String pe1, String pe2, String re1, String re2, String re3) {
        initComponents();
        this.setLocationRelativeTo(null);
        Pe1.setText(pe1);
        Pe2.setText(pe2);
        LlenarDatos(pe1, pe2, re1, re2, re3);
        Motivo.setVisible(false);
        TextoMotivo.setVisible(false);
        Finalmente.setVisible(false);
        this.rellenarTabla(DatosPe1);
        this.rellenarTabla(DatosPe2);
    }

    private boolean verificacion() {
        try {
            // Obtenemos los valores de los 6 JTextField
            int v1 = Integer.parseInt(CaRoundJu1.getText().trim());
            int v1p2 = Integer.parseInt(CaRoundJu1P2.getText().trim());

            int v2 = Integer.parseInt(CaRoundJu2.getText().trim());
            int v2p2 = Integer.parseInt(CaRoundJu2P2.getText().trim());

            int v3 = Integer.parseInt(CaRoundJu3.getText().trim());
            int v3p2 = Integer.parseInt(CaRoundJu3P2.getText().trim());

            // Validamos que todos estén en el rango 7–10
            if ((v1 >= 7 && v1 <= 10)
                    && (v1p2 >= 7 && v1p2 <= 10)
                    && (v2 >= 7 && v2 <= 10)
                    && (v2p2 >= 7 && v2p2 <= 10)
                    && (v3 >= 7 && v3 <= 10)
                    && (v3p2 >= 7 && v3p2 <= 10)) {
                // Guardamos en los ArrayList de cada juez
                nuevaPelea.ju[0].puntos1.add(v1);
                nuevaPelea.ju[0].puntos2.add(v1p2);

                nuevaPelea.ju[1].puntos1.add(v2);
                nuevaPelea.ju[1].puntos2.add(v2p2);

                nuevaPelea.ju[2].puntos1.add(v3);
                nuevaPelea.ju[2].puntos2.add(v3p2);

                return true;
            } else {
                new MensajeError(null, true).show();
                return false;
            }
        } catch (NumberFormatException e) {
            // Si alguno no es número válido
            new MensajeError(null, true).show();
            return false;
        }
    }

    public void LlenarDatos(String p1, String p2, String r1, String r2, String r3) {

        nuevaPelea.designarJuez(r1, r2, r3);
        nuevaPelea.configurarPeleador(p1, 0);
        nuevaPelea.configurarPeleador(p2, 1);
        nuevaPelea.mostrarPeleadores();
    }

    public void rellenarTabla(javax.swing.JTable tabla) {
        // Creamos un modelo con 1 columna y 5 filas
        DefaultTableModel modelo = new DefaultTableModel(5, 1);

        Random rand = new Random();

        for (int i = 0; i < 4; i++) {
            int numero = rand.nextInt(50) + 1; // aleatorio entre 1 y 50
            modelo.setValueAt(numero, i, 0);   // fila i, columna 0
        }
        // Última fila: caídas menos probables
        int prob = rand.nextInt(10); // valores 0–9
        int caida;
        if (prob == 0) {
            // Solo 1 de cada 10 veces hay caída
            caida = rand.nextInt(2) + 1; // caída de 1 o 2
        } else {
            caida = 0; // sin caída
        }
        modelo.setValueAt(caida, 4, 0); // fila 4 (quinta fila), columna 0

        // Asignamos el modelo al JTable
        tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Pe2 = new javax.swing.JLabel();
        Contador = new javax.swing.JLabel();
        Pe1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Siguiente = new javax.swing.JButton();
        Terminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DatosPe1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        DatosPe2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Motivo = new javax.swing.JTextField();
        TextoMotivo = new javax.swing.JLabel();
        Finalmente = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        CaRoundJu1 = new javax.swing.JTextField();
        CaRoundJu2 = new javax.swing.JTextField();
        CaRoundJu3 = new javax.swing.JTextField();
        CaRoundJu2P2 = new javax.swing.JTextField();
        CaRoundJu1P2 = new javax.swing.JTextField();
        CaRoundJu3P2 = new javax.swing.JTextField();
        Pe3 = new javax.swing.JLabel();
        Pe4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        Pe2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pe2.setForeground(new java.awt.Color(0, 0, 0));
        Pe2.setText("peleador 2");

        Contador.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Contador.setForeground(new java.awt.Color(0, 0, 0));
        Contador.setText("1");

        Pe1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pe1.setForeground(new java.awt.Color(0, 0, 0));
        Pe1.setText("peleador 1");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Round no. ");

        Siguiente.setBackground(new java.awt.Color(204, 255, 204));
        Siguiente.setForeground(new java.awt.Color(0, 0, 0));
        Siguiente.setText("Siguiente round");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });

        Terminar.setBackground(new java.awt.Color(255, 0, 51));
        Terminar.setForeground(new java.awt.Color(0, 0, 0));
        Terminar.setText("Terminar Pelea");
        Terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TerminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Japs:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Cross:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Uppers:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Ganchos");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Caidas");

        DatosPe1.setBackground(new java.awt.Color(255, 255, 255));
        DatosPe1.setForeground(new java.awt.Color(0, 0, 0));
        DatosPe1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Puntos"
            }
        ));
        DatosPe1.setRowHeight(25);
        jScrollPane2.setViewportView(DatosPe1);

        DatosPe2.setBackground(new java.awt.Color(255, 255, 255));
        DatosPe2.setForeground(new java.awt.Color(0, 0, 0));
        DatosPe2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Puntos"
            }
        ));
        DatosPe2.setRowHeight(25);
        jScrollPane3.setViewportView(DatosPe2);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Japs:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Cross:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Uppers:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Ganchos");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Caidas");

        Motivo.setBackground(new java.awt.Color(255, 255, 255));
        Motivo.setText("Motivo");
        Motivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MotivoMouseClicked(evt);
            }
        });
        Motivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotivoActionPerformed(evt);
            }
        });

        TextoMotivo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TextoMotivo.setForeground(new java.awt.Color(0, 0, 0));
        TextoMotivo.setText("Razon por terminar: ");

        Finalmente.setBackground(new java.awt.Color(255, 0, 51));
        Finalmente.setForeground(new java.awt.Color(0, 0, 0));
        Finalmente.setText("Terminar");
        Finalmente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinalmenteActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Calificación Juez 3:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Calificación Juez 1:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Calificación Juez 2:");

        CaRoundJu1.setText("0");
        CaRoundJu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaRoundJu1MouseClicked(evt);
            }
        });

        CaRoundJu2.setText("0");
        CaRoundJu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaRoundJu2ActionPerformed(evt);
            }
        });

        CaRoundJu3.setText("0");
        CaRoundJu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaRoundJu3ActionPerformed(evt);
            }
        });

        CaRoundJu2P2.setText("0");
        CaRoundJu2P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaRoundJu2P2MouseClicked(evt);
            }
        });

        CaRoundJu1P2.setText("0");
        CaRoundJu1P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaRoundJu1P2MouseClicked(evt);
            }
        });

        CaRoundJu3P2.setText("0");
        CaRoundJu3P2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CaRoundJu3P2MouseClicked(evt);
            }
        });

        Pe3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pe3.setForeground(new java.awt.Color(0, 0, 0));
        Pe3.setText("P2");

        Pe4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Pe4.setForeground(new java.awt.Color(0, 0, 0));
        Pe4.setText("P1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(Pe1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pe2)
                .addGap(112, 112, 112))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Contador)
                        .addGap(174, 174, 174))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextoMotivo)
                        .addComponent(Motivo)
                        .addComponent(Finalmente, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CaRoundJu3, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(CaRoundJu2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(CaRoundJu1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Pe4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CaRoundJu1P2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Pe3))
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Terminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(CaRoundJu2P2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CaRoundJu3P2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contador)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pe1)
                    .addComponent(Pe2))
                .addGap(4, 4, 4)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pe3)
                    .addComponent(Pe4)
                    .addComponent(Siguiente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Terminar)
                    .addComponent(CaRoundJu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaRoundJu1P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextoMotivo)
                    .addComponent(jLabel14)
                    .addComponent(CaRoundJu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CaRoundJu2P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Motivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(CaRoundJu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CaRoundJu3P2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(Finalmente)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TerminarActionPerformed
        Motivo.setVisible(true);
        TextoMotivo.setVisible(true);
        Finalmente.setVisible(true);
        Terminar.setVisible(false);
    }//GEN-LAST:event_TerminarActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed

        if (c < 12) {
            //hay menos de 12 rounds
            if (verificacion() == true) {
                //checamos las condiciones para avisar
                this.rellenarTabla(DatosPe1);
                this.rellenarTabla(DatosPe2);
                c++;
                Contador.setText(String.valueOf(c));
            }

        } else {
            //imprimimos resultados
            Resultados fin = new Resultados(nuevaPelea);
            fin.setVisible(true);
            this.setVisible(false);
        }


    }//GEN-LAST:event_SiguienteActionPerformed

    private void MotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MotivoActionPerformed

    private void MotivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MotivoMouseClicked
        // TODO add your handling code here:
        Motivo.setText("");
    }//GEN-LAST:event_MotivoMouseClicked

    private void FinalmenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinalmenteActionPerformed
        // TODO add your handling code here:
        nuevaPelea.MotivoFin = Motivo.getText();
        //Espera
        Resultados fin = new Resultados(nuevaPelea);
        fin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_FinalmenteActionPerformed

    private void CaRoundJu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaRoundJu2ActionPerformed
        // TODO add your handling code here:
        CaRoundJu2.setText("");
    }//GEN-LAST:event_CaRoundJu2ActionPerformed

    private void CaRoundJu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaRoundJu1MouseClicked
        // TODO add your handling code here:
        CaRoundJu1.setText("");
    }//GEN-LAST:event_CaRoundJu1MouseClicked

    private void CaRoundJu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaRoundJu3ActionPerformed
        // TODO add your handling code here:
        CaRoundJu3.setText("");
    }//GEN-LAST:event_CaRoundJu3ActionPerformed

    private void CaRoundJu2P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaRoundJu2P2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CaRoundJu2P2MouseClicked

    private void CaRoundJu1P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaRoundJu1P2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CaRoundJu1P2MouseClicked

    private void CaRoundJu3P2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CaRoundJu3P2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CaRoundJu3P2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaRoundJu1;
    private javax.swing.JTextField CaRoundJu1P2;
    private javax.swing.JTextField CaRoundJu2;
    private javax.swing.JTextField CaRoundJu2P2;
    private javax.swing.JTextField CaRoundJu3;
    private javax.swing.JTextField CaRoundJu3P2;
    private javax.swing.JLabel Contador;
    private javax.swing.JTable DatosPe1;
    private javax.swing.JTable DatosPe2;
    private javax.swing.JButton Finalmente;
    private javax.swing.JTextField Motivo;
    private javax.swing.JLabel Pe1;
    private javax.swing.JLabel Pe2;
    private javax.swing.JLabel Pe3;
    private javax.swing.JLabel Pe4;
    private javax.swing.JButton Siguiente;
    private javax.swing.JButton Terminar;
    private javax.swing.JLabel TextoMotivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
